export const localization = {
    NavBar: {
        title: "Traceability of covid 19 vaccine",
        initialProcess: "Initial Process",
        warehouse: "Warehouse",
        distributor: "Distributor",
        station: "Station",
        searchPlaceHolder: "Search batch no,...",
        connect: "Connect Wallet",
        objectInjection: "Object Injection"
    },
    Dashboard: {
        dashboard: "Dashboard",
        progress: "Total progress",
        warehouse: "Warehouse",
        distributor: "Distributor",
        vaccinationStation: "Vaccination Station",
        activity: "Latest Activity",
        batchNo: "Batch No.",
        producer: "Producer",
        station: "Station",
        addProcess: "Add Process",
    },
    CreateProcess: {
        newProcess: "New Process",
        createProcessForm: "Create Process Form",
        producerName: "Producer Name",
        enterProducerName: "Enter producer name",
        warehouse: "Warehouse",
        enterWarehouse: "Enter warehouse name",
        distributor: "Distributor",
        enterpriseDistributorName: "Enter distributor name",
        vaccinationStation: "Vaccination Station",
        enterVaccinationStation: "Enter vaccination station name",
        createProcess: "Create process",
        cancel: "Cancel",
        preview: "Preview",
        producerNameP: "Producer Name :",
        warehouseNameP: "Warehouse Name :",
        distributorNameP: "Distributor Name :",
        vaccinationStationNameP: 'Vaccination Station :',
        totalWeightNameP: 'Total Weight :',
        weight: "Total Weight",
        enterWeight: "Enter total weight",
    },

    WarehouseDashboard: {
        warehouse: "Warehouse",
        addConsignments: "Add Consignments",
        success: "Success",
        failure: "Failure",
    },
    CreateConsignment: {
        newConsignment: "New Consignments",
        createWarehouse: "Create Warehouse",
        preview: "Preview",
        batchNo: "Batch no",
        enterBatchNo: "Enter batch no",
        vaccineName: "Vaccine Name",
        enterVaccineName: "Enter vaccine name",
        quantity: "Quantity",
        enterquantity: "Enter quantity",
        price: "Price",
        enterPrice: "Enter price",
        optimumTemperature: "Optimum Temperature",
        enterOptimumTemperature: "Enter optimum temperature",
        optimumHumidity: "Optimum Humidity",
        enterOptimumHumidity: "Enter optimum humidity",
        storageDate: "Storage Date",
        enterStorageDate: "Enter storage date",
        violation: "Violation",
        isViolation: "No",
        cancel: "Cancel",
        batchNoP: "Batch no:",
        vaccineNameP: "Vaccine Name:",
        quantityP: "Quantity:",
        priceP: "Price:",
        optimumTemperatureP: "Optimum Temperature:",
        optimumHumP: "Optimum Humidity:",
        storageDateP: "Storage Date:",
        violationP: "Violation:",
        emtyValue: "___________________"
    }
}