export const localization = {
  NavBar: {
    title: "Traceability of covid 19 vaccine",
    initialProcess: "Logistics",
    warehouse: "Warehouse",
    distributor: "Distributor",
    station: "Station",
    searchPlaceHolder: "Search batch no,...",
    connect: "Connect Wallet",
    objectInjection: "Object Injection",
  },
  Dashboard: {
    dashboard: "Manage Logistics",
    progress: "Total progress",
    warehouse: "Warehouse",
    distributor: "Distributor",
    vaccinationStation: "Vaccination Station",
    activity: "Latest Activity",
    batchNo: "Batch No.",
    producer: "Producer",
    station: "Station",
    addProcess: "Add Process",
  },
  CreateProcess: {
    newProcess: "Logistic Form",
    createProcessForm: "Create Logistic Form",
    producerName: "Producer Name",
    enterProducerName: "Enter producer name",
    warehouse: "Warehouse",
    enterWarehouse: "Enter warehouse name",
    distributor: "Distributor",
    enterpriseDistributorName: "Enter distributor name",
    vaccinationStation: "Vaccination Station",
    enterVaccinationStation: "Enter vaccination station name",
    createProcess: "Create process",
    cancel: "Cancel",
    preview: "Preview",
    producerNameP: "Producer Name  :",
    warehouseNameP: "Warehouse Name  :",
    distributorNameP: "Distributor Name  :",
    vaccinationStationNameP: "Vaccination Station :",
    totalWeightNameP: "Quantity :",
    weight: "Quantity",
    enterWeight: "Enter quantity",
  },

  WarehouseDashboard: {
    warehouse: "Warehouse",
    addConsignments: "Add Consignments",
    success: "Success",
    failure: "Failure",
  },
  CreateConsignment: {
    newConsignment: "New Consignments",
    createWarehouse: "Create Warehouse",
    preview: "Preview",
    batchNo: "Batch no",
    enterBatchNo: "Enter batch no",
    vaccineName: "Vaccine Name",
    enterVaccineName: "Enter vaccine name",
    quantity: "Quantity",
    enterquantity: "Enter quantity",
    price: "Price",
    enterPrice: "Enter price",
    optimumTemperature: "Optimum Temperature",
    enterOptimumTemperature: "Enter optimum temperature (example: 10 - 15)",
    optimumHumidity: "Optimum Humidity",
    enterOptimumHumidity: "Enter optimum humidity (example: 10 - 15)",
    storageDate: "Storage Date",
    enterStorageDate: "Enter storage date",
    violation: "Violation",
    isViolation: "No",
    cancel: "Cancel",
    batchNoP: "Batch no :",
    vaccineNameP: "Vaccine Name :",
    quantityP: "Quantity :",
    priceP: "Price :",
    optimumTemperatureP: "Optimum Temperature :",
    optimumHumP: "Optimum Humidity :",
    storageDateP: "Storage Date :",
    violationP: "Violation :",
    emtyValue: "____________",
  },
  DistributorDashboard: {
    distributor: "Distributor",
    success: "Success",
    failure: "Failure",
    lastestActivity: "Latest Ativity",
    newDistributor: "New Distributor",
    addDistributor: "Add Distributor",
    createDistributor: "Create Distributor",
    batchNo: "Batch no",
    enterBatchNo: "Enter batch no",
    shippingName: "Shipping Name",
    enterShippingName: "Enter shipping name",
    shippingNo: "Shipping No",
    enterShippingNo: "Enter shipping no",
    quantity: "Quantity",
    enterQuantity: "Enter quantity",
    departureDateTime: "Departure Date Time",
    enterDepartureDateTime: "Enter departure date time",
    estimateDateTime: "Estimate Date Time",
    enterEstimateDateTime: "Enter estimate date time",
    distributorId: "Distributor Id",
    enterDistributorId: "Enter distributor id",
    optimumTemperature: "Optimum Temperature",
    enterOptimumTemperature: "Enter optimum temperature",
    optimumHumidity: "Optimum Humidity",
    enterOptimumHumidity: "Enter optimum humidity",
    createDistributor: "Create distributor",
    cancel: "Cancel",
    preview: "Preview",
    batchNoP: "Batch no :",
    shippingNameP: "Shipping Name :",
    shippingNoP: "Shipping No :",
    quantityP: "Quantity :",
    departureDateTimeP: "Departure Date Time :",
    estimateDateTimeP: "Estimate Date Time :",
    distributorIdP: "Distributor Id :",
    optimumTemperatureP: "Optimum Temperature :",
    optimumHumidityP: "Optimum Humidity  :",
    emtyValue: "____________",
  },

  station: {
    vaccinationStation: "Vaccination Station",
    addStation: "Add Station",
    success: "Success",
    failure: "Failure",
    newStation: "New Station",
    createStation: "Create Station",
    batchNo: "Batch No",
    enterBatchNo: "Enter batch no",
    quantity: "Quantity",
    enterQuantity: " Enter quantity",
    arrivalDateTime: "Arrival Date Time",
    enterArrivalDateTime: "Enter arrival date time",
    vaccinationStationId: "Vaccination Station Id",
    enterVaccinationStationId: "Enter vaccinantion station id",
    shippingName: "Shipping Name",
    enterShippingName: "Enter shipping name",
    shippingNo: "Shipping No",
    enterShippingNo: "Enter shipping no",
    preview: "Preview",
    batchNoP: "Batch No :",
    quantityP: "Quantity :",
    arrivalDateTimeP: "Arrival Date Time :",
    vaccinationStationIdP: "Vaccination Station Id :",
    shippingNameP: "Shipping Name :",
    shippingNoP: "Shipping No :",
    createDistributor: "Create distributor",
    cancel: "Cancel",
    emtyValue: "____________",
  },

  person: {
    vaccinationPerson: "Vaccination Person",
    addPerson: "Vaccination Person",
    success: "Success",
    failure: "Failure",
    newPerson: "New Person",
    createPerson: "Create Person",
    batchNo: "Batch no",
    enterBatchNo: "Enter batch no",
    personName: "Person Name",
    enterPersonName: "Enter person name",
    age: "Age",
    enterAge: "Enter age",
    indetityCard: "Indetity Card",
    enterIndentityCard: "Enter identity card",
    numberOfVaccination: "Number Of Vaccination",
    enterNumberOfVaccination: "Enter number of Vaccination",
    vaccinationDate: "Vaccination Date",
    enterVaccinationDate: "Enter vaccination date",
    typeOfVaccine: "Type of Vaccine",
    enterTypeOfVaccine: "Enter type of vaccine",
    createPerson: "Create Person",
    cancel: "Cancel",
    batchNoP: "Batch No : ",
    personNameP: "Person Name :",
    ageP: "Age :",
    indetityCardP: "Identity Card",
    numberOfVaccineP: "Number of Vaccine :",
    vaccinationDateP: "Vaccination Date :",
    typeOfVaccineP: "Type Of Vaccine :",
    emtyValue: "____________",
    preview: "Preview"
  },
};
